### ISSUE TITLE
Collected Exporter with heavy load 

### ISSUE THREAD

**Issue by ADI10HERO** [prometheus/collectd_exporter#101]
Can I use 1 collectd-exporter instance to accept metrics from 5-6 VM's collectd? Each sending using binary network protocol every 5-10 secs? 

Collectd exporter can handle that load right?

**Comment by SuperQ** [comment]
It's best to run one collectd_exporter per node and send collectd traffic over localhost. This scales best.

**Comment by ADI10HERO** [comment]
Can you elaborate on it a little?

I have a VM where prometheus and collectd-exporter are running... Lets call it 'X'

I am using collectd on those 5 nodes (VMs) lets call them A, B, C, D, E

So do you want me to run 5 collectd-exporter's like X_A, X_B, X_C, X_D and X_E ?
All 5 X_* run on the VM X?

And then these 5 send data over localhost to prometheus? 

Is this what you meant?

**Comment by SuperQ** [comment]
No, you run collectd_exporter on each node, A,B,C... Then Prometheus on host X is configured to scrape the exporter on `http://A:9103/metrics`, `http://B:9103/metrics`, etc.

**Comment by ADI10HERO** [comment]
So all collectds send to collectd-exporters on the localhost?
And the scraping work will be done by prometheus?
Is this right?

If yes, That's smart! :D

Thankyou so much :)

**Comment by SuperQ** [comment]
Yes, that's exactly it.
