### ISSUE TITLE
Blocked in collectd server

### ISSUE THREAD

**Issue by gambol99** [prometheus/collectd_exporter#14]
Experiencing a very weird issue ... (Note: i'm using the prom/collectd-exporter:latest) I get;

    /bin $ /bin/collectd_exporter -collectd.listen-address=":25826" 
    panic: runtime error: index out of range
    
    goroutine 1 [running]:
    net.IP.IsMulticast(0x0, 0x0, 0x0, 0x6)
    	/usr/local/go/src/net/ip.go:132 +0x9b
    collectd.org/network.(*Server).ListenAndWrite(0xc20802e5a0, 0x0, 0x0)
    	/app/.build/gopath/src/collectd.org/network/server.go:49 +0x125
    main.startCollectdServer(0x7fe1919972c0, 0xc20800aa80)
    	/app/main.go:247 +0x284
    main.main()
    	/app/main.go:256 +0xa2
    
    goroutine 7 [select]:
    main.(*collectdCollector).processSamples(0xc20800aa80)
    	/app/main.go:156 +0x43f
    created by main.newCollectdCollector
    	/app/main.go:131 +0x118

I can avoid this by using the -collectd.listen-address="0.0.0.0:25826", however, whenever the collectd interface is enabled, the prometheus endpoint is never started. 

    [jest@starfury services]$ netstat -antu | grep 9103
    [jest@starfury services]$ netstat -antu | grep 25826
    udp6       0      0 :::25826                :::* 

i.e. it never gets to the http.ListenAndServe(*webAddress, nil) line

    [jest@starfury services]$ ps aux | grep collect
    jest     14923  0.0  0.0   8648  4512 pts/0    Sl+  13:33   0:00 ./collectd_exporter -collectd.listen-address=0.0.0.0:25826
    jest     14952  0.0  0.0 114332  2320 pts/1    S+   13:35   0:00 grep --color=auto collect
    
    goroutine 9 [syscall]:
    runtime.notetsleepg(0x96e0b8, 0xdf845c6cf, 0x0)
    	/usr/lib/golang/src/runtime/lock_futex.go:201 +0x52 fp=0xc20801d768 sp=0xc20801d740
    runtime.timerproc()
    	/usr/lib/golang/src/runtime/time.go:207 +0xfa fp=0xc20801d7e0 sp=0xc20801d768
    runtime.goexit()
    	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
    created by runtime.addtimerLocked
    	/usr/lib/golang/src/runtime/time.go:113 +0x1ba
    
    goroutine 1 [IO wait]:
    net.(*pollDesc).Wait(0xc208010ae0, 0x72, 0x0, 0x0)
    	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
    net.(*pollDesc).WaitRead(0xc208010ae0, 0x0, 0x0)
    	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
    net.(*netFD).Read(0xc208010a80, 0xc20809c000, 0x5ac, 0x5ac, 0x0, 0x7f055a63cc68, 0xc208032c18)
    	/usr/lib/golang/src/net/fd_unix.go:242 +0x40f
    net.(*conn).Read(0xc208036050, 0xc20809c000, 0x5ac, 0x5ac, 0x5ac, 0x0, 0x0)
    	/usr/lib/golang/src/net/net.go:121 +0xdc
    collectd.org/network.(*Server).ListenAndWrite(0xc2080385a0, 0x0, 0x0)
    	/home/jest/go/src/github.com/gambol99/collectd_exporter/.build/gopath/src/collectd.org/network/server.go:76 +0x323
    main.startCollectdServer(0x7f055a63d2c0, 0xc20800aa80)
    	/home/jest/go/src/github.com/gambol99/collectd_exporter/main.go:247 +0x284
    main.main()
    	/home/jest/go/src/github.com/gambol99/collectd_exporter/main.go:256 +0xa2
    
    goroutine 7 [select]:
    main.(*collectdCollector).processSamples(0xc20800aa80)
    	/home/jest/go/src/github.com/gambol99/collectd_exporter/main.go:156 +0x43f
    created by main.newCollectdCollector
    	/home/jest/go/src/github.com/gambol99/collectd_exporter/main.go:131 +0x118
    
    rax     0xfffffffffffffffc
    rbx     0x3b9938cf
    rcx     0x440503

You can see the main go routine inside the collectd code waiting for metrics to come in.  The issue appears to be [line 247](https://github.com/prometheus/collectd_exporter/blob/master/main.go#L247)

    go log.Fatal(srv.ListenAndWrite())

Changing this to allow srv.ListenAndWrite() to run within the scope of the goroutine fixed the issue for me 
	
	go func() {
		log.Fatal(srv.ListenAndWrite())
	}()

[jest@starfury services]$ netstat -antu | grep 25826
udp6       0      0 :::25826                :::*                               
[jest@starfury services]$ netstat -antu | grep 9103
tcp6       0      0 :::9103                 :::*                    LISTEN  

I'll raise a PR for it?

**Comment by brian-brazil** [comment]
This seems very odd, what version of Go are you using?

**Comment by gambol99** [comment]
[jest@starfury collectd_exporter]$ go version
go version go1.4.2 linux/amd64

... Although I'm seeing the same issue with the prom/collectd-exporter off docker hub ... I was using the kubernetes pod file below. But no matter what i do I can only get either the collectd or the prometheus port to work ... not both, hence why i forked to look at the code.

    apiVersion: v1
    kind: ReplicationController
    metadata:
      name: collectd-exporter
    spec:
      replicas: 1
      selector:
        name: collectd-exporter
      template:
        metadata:
          labels:
            name: collectd-exporter
          annotations:
            metrics: |
              - name: collectd-exporter
                port: 9103
        spec:
          containers:
          - name: collectd
            image: prom/collectd-exporter
            args:
            - -web.listen-address="0.0.0.0:9103"
            - -collectd.listen-address=0.0.0.0:25826
            ports:
            - containerPort: 25826
              protocol: UDP
            - containerPort: 9103
            #livenessProbe:
            #  httpGet:
            #    path: /metrics
            #    port: 9103
            #  initialDelaySeconds: 120
            #  timeoutSeconds: 10
          imagePullPolicy: Always

**Comment by brian-brazil** [comment]
Looks like this was introduced with #9 and is fixed now, thanks.
