### ISSUE TITLE
Release 0.1.0 - 05.05.2015 does not work

### ISSUE THREAD

**Issue by cgrinds** [prometheus/collectd_exporter#16]
The documentation for collectd_exporter does not match the version in the release tab - perhaps it's old?

./collectd_exporter -collectd.listen-address=":25826"
flag provided but not defined: -collectd.listen-address

**Comment by juliusv** [comment]
For a particular version, you can always list available flags like this:

```
./collectd_exporter -h
Usage of ./collectd_exporter:
  -web.collectd-push-path="/collectd-post": Path under which to accept POST requests from collectd.
  -web.listen-address=":9103": Address on which to expose metrics and web interface.
  -web.telemetry-path="/metrics": Path under which to expose Prometheus metrics.
```

But anyways, 0.1.0 is hideously old and there've been fixes and changes since then. I will do a 0.2.0 release now.

**Comment by cgrinds** [comment]
I listed the available flags, but wasn't sure how to translate those options to the current readme since the new version also supports all those options.

Either way, thanks for updating the release!

**Comment by juliusv** [comment]
Yup. See https://github.com/prometheus/collectd_exporter/pull/17 for the release PR.

**Comment by juliusv** [comment]
@cgrinds Released 0.2.0 at https://github.com/prometheus/collectd_exporter/releases/tag/0.2.0. Only uploaded the 64-bit Linux tarball for it for now. We can add Mac and 32 bit later if needed.

**Comment by juliusv** [comment]
Think this can be closed then?

**Comment by cgrinds** [comment]
@juliusv Yes. Thanks again
