### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by iorlas** [prometheus/collectd_exporter#18]
I run exporter with docker: `docker run -p 9103:9103 prom/collectd-exporter:latest -collectd.listen-address=":25826"` and this is what I got:

panic: runtime error: index out of range

goroutine 10 [running]:
net.IP.IsMulticast(0x0, 0x0, 0x0, 0x6)
	/usr/local/go/src/net/ip.go:132 +0x9b
collectd.org/network.(*Server).ListenAndWrite(0xc20802e5a0, 0x0, 0x0)
	/app/.build/gopath/src/collectd.org/network/server.go:49 +0x125
main.func·001()
	/app/main.go:248 +0x27
created by main.startCollectdServer
	/app/main.go:249 +0x2c2

goroutine 1 [chan receive]:
github.com/prometheus/client_golang/prometheus.(*registry).Register(0xc2080300c0, 0x7f5290535488, 0xc208032210, 0x0, 0x0, 0x0, 0x0)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:233 +0x247
github.com/prometheus/client_golang/prometheus.(*registry).RegisterOrGet(0xc2080300c0, 0x7f5290535488, 0xc208032210, 0x0, 0x0, 0x0, 0x0)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:296 +0x69
github.com/prometheus/client_golang/prometheus.RegisterOrGet(0x7f5290535488, 0xc208032210, 0x0, 0x0, 0x0, 0x0)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:136 +0x62
github.com/prometheus/client_golang/prometheus.MustRegisterOrGet(0x7f5290535488, 0xc208032210, 0x0, 0x0)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:142 +0x44
github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts(0x0, 0x0, 0x7ba390, 0x4, 0x7f7410, 0x13, 0x8123d0, 0x21, 0xc20803d320, 0x0, ...)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/http.go:132 +0x286
github.com/prometheus/client_golang/prometheus.InstrumentHandlerFunc(0x7d49d0, 0xa, 0xc20800abc0, 0x7f52905353b0)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/http.go:73 +0x107
github.com/prometheus/client_golang/prometheus.InstrumentHandler(0x7d49d0, 0xa, 0x7f52905353b0, 0xc2080300c0, 0xc20803ca80)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/http.go:61 +0x98
github.com/prometheus/client_golang/prometheus.Handler(0x0, 0x0)
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:91 +0x73
main.main()
	/app/main.go:264 +0x12a

goroutine 7 [select]:
main.(*collectdCollector).processSamples(0xc20800ab60)
	/app/main.go:156 +0x43f
created by main.newCollectdCollector
	/app/main.go:131 +0x118

goroutine 11 [runnable]:
github.com/prometheus/client_golang/prometheus.func·011()
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:220
created by github.com/prometheus/client_golang/prometheus.(*registry).Register
	/app/.build/gopath/src/github.com/prometheus/client_golang/prometheus/registry.go:223 +0x154

**Comment by juliusv** [comment]
Thanks, getting the same (also outside of Docker, it's not related). It seems like the collectd Go library doesn't allow a listening address without an IP, like it's otherwise common in Go. It just crashes in that case :( We'll have to work around that or fix it upstream, but for now I'd recommend using `localhost:25826` instead of `:25826`.

**Comment by juliusv** [comment]
Filed an issue against go-collectd: https://github.com/collectd/go-collectd/issues/12

**Comment by octo** [comment]
Should be fixed upstream. Thanks for reporting this, @iorlas!

**Comment by iorlas** [comment]
Thank you, guys  :+1:

**Comment by juliusv** [comment]
Nice!
