### ISSUE TITLE
how to define collectd_exporter with collectd_listen_address over collected_exporter image?

### ISSUE THREAD

**Issue by sandeeppromtest** [prometheus/collectd_exporter#25]
how exporter will accepts collectd network plugin metrics on port "25826" nothing has been give in "README". 

Where to define collectd_exporter with -collectd.listen-address=":25826"? 

We have just taken collectd_exporter image and it's running collectd_exporter over port ":9103", how it will collect network metrics over port ":25826"?

**Comment by juliusv** [comment]
It's just a command-line flag. You can pass it like this:

```bash
./collectd_exporter -collectd.listen-address=":25826"
```

Note that it will still *also* listen on port 9103 for serving Prometheus metrics (that is controlled by the flag `web.listen-address`).

If you are using Docker, you can do:

```bash
docker run -d -p 9103:9103 -p 25826:25826 prom/collectd-exporter -collectd.listen-address=":25826"
```

**Comment by roshu10** [comment]
hey,

I'm using docker.

But when i do, **telnet localhost 25826** in prometheus server, connection refused error is coming

**Comment by octo** [comment]
@roshu10 *collectd* is using UDP for communication, telnet is using TCP. That's why the connection attempt will fail.

HTH,
—octo
