### ISSUE TITLE
make breaks on CentOS 7.2

### ISSUE THREAD

**Issue by tzach** [prometheus/collectd_exporter#29]
This change was in the last few days.
I had a script which install collectd_exporter as follow:
```
git clone https://github.com/prometheus/collectd_exporter
cd collectd_exporter
make
```

Now, I get the following:
```
$ make
>> formatting code
can't load package: package _/home/centos/collectd_exporter: cannot find package "_/home/centos/collectd_exporter" in any of:
        /usr/lib/golang/src/_/home/centos/collectd_exporter (from $GOROOT)
        ($GOPATH not set)
make: *** [format] Error 1
```
Running on CentOS 7.2

**Comment by juliusv** [comment]
As per equivalent mailing list thread, `make` expects a working Go environment (including `GOPATH`) now: https://groups.google.com/forum/#!topic/prometheus-developers/Mk2WPTW3Edk

Closing here.
