### ISSUE TITLE
imports context: unrecognized import path "context"

### ISSUE THREAD

**Issue by flyinva** [prometheus/collectd_exporter#37]
Hi,

I tried to get collectd_exporter with `go get` command and this error is triggered :

```
$ go get github.com/prometheus/collectd_exporter
package github.com/prometheus/collectd_exporter
    imports collectd.org/api
    imports context: unrecognized import path "context"
```

**Comment by octo** [comment]
Hi @flyinva,

the `context` package has been added in Go 1.7 and is required to build *collectd_exporter*.

Best regards,
—octo

**Comment by flyinva** [comment]
Go 1.7 is only available in Debian testing. I will have to wait some times for this version in backports.

**Comment by octo** [comment]
It's very unfortunate that there is no good transition path from the old (experimental) `x/net/context` package and the Go 1.7 `context` package :\

One thing we can consider is add an appropriate *build constraint*, like:

    // +build go1.7

However, the error message when building with earlier versions of Go is something along the lines of:

    go build github.com/prometheus/collectd_exporter: no buildable Go source files in $GOPATH/src/github.com/prometheus/collectd_exporter

I'm not sure this error message is an improvement though :\

**Comment by flyinva** [comment]
collectd_exporter can be build with Go 1.7 on Debian SID (and probably any other distrib) and run on Debian Jessie.

**Comment by padgyx** [comment]
go get github.com/prometheus/prometheus/cmd/promtool
package context: unrecognized import path "context" (import path does not begin with hostname)

**Comment by briffle** [comment]
@padgyx  I had the exact same error on centos 7.  It runs a very old version of golang (1.6.3) I used this repo and instructions to update, and its working well:
https://go-repo.io/

specifically:
```
sudo rpm --import https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO
curl -s https://mirror.go-repo.io/centos/go-repo.repo | tee /etc/yum.repos.d/go-repo.repo
sudo yum update golang
```

**Comment by AlexN93** [comment]
I'm having the exact same problem and I'm running go version go1.2.1 linux/amd64 on Ubuntu 14 virtual machine.

**Comment by brian-brazil** [comment]
You generally need the latest version of Go when building Go components of Prometheus, with the exception of using client_golang which currently supports back to Go 1.7.

**Comment by yassermog** [comment]
xport GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin
