### ISSUE TITLE
in which config file can i add more collectd plugins?

### ISSUE THREAD

**Issue by oviis** [prometheus/collectd_exporter#38]

**Comment by brian-brazil** [comment]
That would be the collectd config file, though we'd recommend using the node exporter or application specific exporters instead.

**Comment by oviis** [comment]
Thanks for the very very fast reply 👍 
Can you please give me the exactly location, is it the "/etc/collectd/collectd.conf"? 
the node exporter cannot catch all mounting points, to be more specific the AWS EBS mounting points made by Kubernetes, because this mounting points are in locations like "/var/lib/kubelet/plugins/kubernetes.io/aws-ebs...."

**Comment by brian-brazil** [comment]
I don't know your system, that's one possible location.

The node exporter should find all mount points. Please file a bug if it can't.

**Comment by oviis** [comment]
Thanks, i have opened a bug
https://github.com/prometheus/node_exporter/issues/332
