### ISSUE TITLE
Not receiving any metrics

### ISSUE THREAD

**Issue by rmwpl** [prometheus/collectd_exporter#39]
Hi, 

I'm trying to use collectd_exporter with collectd 5.4 and Prometheus 0.18.
From the Promdash level I am able to see collectd_exporter_build_info and collectd_last_push_timestamp_seconds, but the latter value us 0.
So the communication between Prometheus and collectd_exporter seems to be working fine.

But it looks like collectd_exporter is not receiving any data from collectd. As I'm on collectd 5.4, I'm trying to use network plugin, since the write_http one does not support JSON format in this version.

Are there any know compatibility problems regarding the binary protocol and/or network plugin itself?

**Comment by rmwpl** [comment]
Managed to solve that by upgrading CollectD.

**Comment by avi-kalar** [comment]
Can you please tell me which version of collectd are you using, I ran into the same issue with collectd_last_push_timestamp_seconds always to 0
