### ISSUE TITLE
Derive type support

### ISSUE THREAD

**Issue by rmwpl** [prometheus/collectd_exporter#42]
Hi there,

I'm trying to use the PostgreSQL CollectD plugin to export metrics to Prometheus.
Most of the stats in PostgreSQL are of the `derive` type, but when I try to plot the graph, it looks like if the type was `gauge`.
I'm using the `:latest` docker image. When I tried to upgrade to `:master`, all the `derive` metrics went away leaving me with no data to work with.

My question is: is the `derive` type supported by exporter?

TIA.

**Comment by octo** [comment]
Hi @rmwpl,

`DERIVE`s are supported, though we recently "fixed" the generated metric names to include a `_total` suffix (#41). This suffix is also used by Prometheus to identify cumulative (non-gauge) metrics.

Best regards,
—octo

**Comment by rmwpl** [comment]
Oh, `_total`, now I get it. Thanks!
I've also found that this can be easily circumvented using the `rate()` Prometheus function.
