### ISSUE TITLE
invalid metric name "collectd_docker_cpu.percent"

### ISSUE THREAD

**Issue by vishksaj** [prometheus/collectd_exporter#46]
Hi Team,

I am getting invalid metric name error in prometheus targets when i configure collectd exporter.
The docker metric  collectd_docker_cpu.percent contains "." which is causing the issue.
Is there any way to fix the issue.

**Comment by vishksaj** [comment]
Also getting 	invalid metric name "collectd_mesos-slave_bytes"

**Comment by hasso** [comment]
In case of binary protocol all metrics used have to be described in types.db file you give to collectd_exporter daemon with -collectd.typesdb-file argument.

**Comment by vishksaj** [comment]
flag provided but not defined: -collectd.typesdb-file

Usage of /bin/collectd_exporter:
  -collectd.auth-file string
        File mapping user names to pre-shared keys (passwords).
  -collectd.listen-address string
        Network address on which to accept collectd binary network packets, e.g. ":25826".
  -collectd.security-level string
        Minimum required security level for accepted packets. Must be one of "None", "Sign" and "Encrypt". (default "None")
  -log.format value
        If set use a syslog logger or JSON logging. Example: logger:syslog?appname=bob&local=7 or logger:stdout?json=true. Defaults to stderr.
  -log.level value
        Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal]. (default info)
  -version
        Print version information.
  -web.collectd-push-path string
        Path under which to accept POST requests from collectd. (default "/collectd-post")
  -web.listen-address string
        Address on which to expose metrics and web interface. (default ":9103")
  -web.telemetry-path string
        Path under which to expose Prometheus metrics. (default "/metrics")

**Comment by nitin02** [comment]
I'm facing a similar issue as well on trying to integrate this (invalid metric names),

https://github.com/signalfx/docker-collectd-plugin

Is there a work-around for this?

**Comment by hasso** [comment]
What's the exact error message?
