### ISSUE TITLE
collectd.listen-address dont change listen port

### ISSUE THREAD

**Issue by patsevanton** [prometheus/collectd_exporter#58]
Hello!
I run collectd_exporter

**collectd_exporter --collectd.listen-address=":25826"**
```
INFO[0000] Starting collectd_exporter (version=0.4.0, branch=HEAD, revision=ad6568ba50d6dabfb03588f42b05adb35fe21019)  source="main.go:303"
INFO[0000] Build context (go=go1.7.6, user=root@ff2f923e5942, date=20180122-15:19:23)  source="main.go:304"
INFO[0000] Listening on :9103                            source="main.go:326"
```

**netstat -tnlp | grep collectd_expor**
`tcp6       0      0 :::9103                 :::*                    LISTEN      2485/collectd_expor `

But collectd.listen-address dont change listen port
How change  listen port ?

**Comment by fbegyn** [comment]
`--web.listen-address=":9103"` is the flag that is responsible for changing the port on which the exporter lists the metrics
`--collectd.listen-address=":25826"` is the port on which the exporter listens for collectd data.

Please close your issue if this is resolved.
