### ISSUE TITLE
MAINTAINER instruction in Dockerfile is deprecated

### ISSUE THREAD

**Issue by tariq1890** [prometheus/collectd_exporter#63]
MAINTAINER should be replaced by LABEL maintainer="..."
See https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

**Comment by yolossn** [comment]
As this has been fixed, Perhaps this Issue can be closed?
https://github.com/prometheus/collectd_exporter/commit/dcbaf3e6f032c12c6734dd621d4b635e79737040
