### ISSUE TITLE
Prometheus collectd-exporter binary for s390x

### ISSUE THREAD

**Issue by aditijadhav38** [prometheus/collectd_exporter#79]
I could see there are binaries available for Prometheus, Prometheus node exporter and Prometheus alertmanager for s390x arch .
Is there any plan to upload binary for collectd-exporter?
Link: https://prometheus.io/download/

**Comment by Nayana-ibm** [comment]
Could you please let us know if binaries for collectd-exporter will be available for s390x?
@brian-brazil  Any idea on this?

**Comment by simonpasquier** [comment]
The current master builds the s390x binaries (check the [artifacts](https://circleci.com/gh/prometheus/collectd_exporter/118#artifacts/containers/0) tab) so they will be available with the next release of the exporter.
FWIW you can build them locally by checking out the repository and running `make promu && promu crossbuild` provided that you've got a working Go 1.12 environment.

**Comment by Nayana-ibm** [comment]
@simonpasquier Thank you for info. Good to see master has s390x artifact. Will wait for latest release.
Also I could build locally but wondering if community can provide direct binaries.

**Comment by Nayana-ibm** [comment]
@simonpasquier just checking if k8s Prometheus adapter has plans to provide s390x binaries also?

**Comment by Nayana-ibm** [comment]
@simonpasquier Any idea when nextrelease is coming up

**Comment by simonpasquier** [comment]
Ping @juliusv

**Comment by Nayana-ibm** [comment]
Binary for s390x is available from v0.5.0.
https://github.com/prometheus/collectd_exporter/releases/download/v0.5.0/collectd_exporter-0.5.0.linux-s390x.tar.gz

Thanks!

**Comment by aditijadhav38** [comment]
Closing it now as binaries are available for s390x.
Thanks!
