### ISSUE TITLE
Prefix to differentiate metrics from different clusters

### ISSUE THREAD

**Issue by smalleni** [prometheus/collectd_exporter#84]
We are trying to migrate from our existing setup of collectd->graphite->grafana to collectd->collectd_exporter->prometheus->grafana. However, we are having difficulty differentiating metrics from different clusters. For example, when using the write_graphite plugin, we could use the prefix keyword to append a custom prefix to metrics that we could use to differentiate metrics from different sources in graphite/grafana.
```
<Plugin write_graphite>
  <Carbon>
    Host "abc.example.com"
    Port "2003"
    Prefix "test."
    Protocol "tcp"
    LogSendErrors true
    StoreRates true
    AlwaysAppendDS false
    EscapeCharacter "_"
  </Carbon>
</Plugin>
```
However, when using the network plugin to send metrics to collectd_exporter there does not seem to be an equivalent "prefix" keyword or similar. So how would one contruct dasbhoards/queries on a per cluster basis (differentiate metrics from different openstack clusters for example,  cluster-1, cluster-2 etc.)

When using collectd_exporter/prometheus we see the exported_instance field in metrics
```
collectd_cpu_total{cpu="0",exported_instance="sai",instance="localhost:9103",job="sai",type="idle"}
```
The exported_instance field refers to the Hostname field in collectd.conf but there does not seem anyway to send a custom keyword/label to differentiate metrics from different clusters.

This is not really an issue, but reaching out for help/guidance. Thanks in advance!

**Comment by matthiasr** [comment]
Please refer to the [community page](https://prometheus.io/community) for the best channels to get help.

That being said, most exporters work with a 1:1 relationship to what they export. In this case, that means having one collectd exporter per source (even per collectd process!). You can then add custom labels to these in Prometheus at the point of [discovery](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).
